name: frondend_application_new
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # TAMBAHKAN BLOK INI UNTUK LOKALISASI YANG BENAR
  flutter_localizations:
    sdk: flutter

  # UI & Fonts
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.8
  collection: ^1.18.0

  # HTTP & Network
  http: ^1.2.1

  # UI Components
  carousel_slider: ^5.0.0

  # Image & Media
  image_picker: ^1.1.2
  image_picker_windows: ^0.2.1+1

  # State Management
  provider: ^6.1.2

  # Storage & Persistence
  shared_preferences: ^2.2.3

  # Utilities
  intl: ^0.20.0 # Pastikan versi ini atau lebih baru
  url_launcher: ^6.3.0

  # Permissions (opsional untuk desktop, tapi baik untuk ada)
  permission_handler: ^11.3.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lapakulbi1.jpg
    - assets/trivo.jpg
    - assets/logo/logolapakulbi.jpg
    - assets/trivo-1.png
    - assets/logo-1.png
    - assets/logo-2.png
